### ISSUE TITLE
collection_prep_add_docs fails with '.AnsibleMapping object' has no attribute 'choices'

### ISSUE THREAD

**Issue by KB-perByte** [ansible-network/collection_prep#58]
### Issue description
Running `collection_prep_add_docs` fails with Traceback 
`jinja2.exceptions.UndefinedError: 'ansible.parsing.yaml.objects.AnsibleMapping object' has no attribute 'choices'`
Also impacts _pre-commit hooks_

### Traceback
```
(dev38)  sagpaul@sagpaul  ~/MyVnvs/WorkA1/collections/ansible_collections/cisco  collection_prep_add_docs -p ./ios 
INFO     Setting collection name to cisco.ios 
INFO     Setting GitHub repository url to https://github.com/ansible-collections/cisco.ios 
INFO     Purging content from directory /home/sagpaul/MyVnvs/WorkA1/collections/ansible_collections/cisco/ios/docs 
INFO     Making docs directory /home/sagpaul/MyVnvs/WorkA1/collections/ansible_collections/cisco/ios/docs 
INFO     Process content in /home/sagpaul/MyVnvs/WorkA1/collections/ansible_collections/cisco/ios/plugins/cliconf 
INFO     Processing /home/sagpaul/MyVnvs/WorkA1/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py 
Traceback (most recent call last): 
 File "/home/sagpaul/MyVnvs/dev38/bin/collection_prep_add_docs", line 8, in <module> 
   sys.exit(main()) 
 File "/home/sagpaul/MyVnvs/dev38/lib/python3.8/site-packages/collection_prep/cmd/add_docs.py", line 548, in main 
   content = process(collection=collection, path=path) 
 File "/home/sagpaul/MyVnvs/dev38/lib/python3.8/site-packages/collection_prep/cmd/add_docs.py", line 385, in process 
   fd.write(template.render(doc)) 
 File "/home/sagpaul/MyVnvs/dev38/lib/python3.8/site-packages/jinja2/environment.py", line 1289, in render 
   self.environment.handle_exception() 
 File "/home/sagpaul/MyVnvs/dev38/lib/python3.8/site-packages/jinja2/environment.py", line 924, in handle_exception 
   raise rewrite_traceback_stack(source=source) 
 File "/home/sagpaul/MyVnvs/dev38/lib/python3.8/site-packages/collection_prep/cmd/plugin.rst.j2", line 102, in top-l
evel template code 
   {% for key, value in options|dictsort recursive %} 
 File "/home/sagpaul/MyVnvs/dev38/lib/python3.8/site-packages/collection_prep/cmd/plugin.rst.j2", line 156, in templ
ate 
   {% if value.default is defined and value.default not in value.choices %} 
jinja2.exceptions.UndefinedError: 'ansible.parsing.yaml.objects.AnsibleMapping object' has no attribute 'choices'
```
_checked with Vyos & Ios_

**Comment by Qalthos** [comment]
Alright, so this appears to be an issue with `jinja2>=3.0.0`. With newer versions of jinja, AnsibleMapping objects are not treated as dict objects are with dot syntax. We probably need to go through plugin.j2 and replace a bunch of `variable.key` with `variable['key']`

**Comment by KB-perByte** [comment]
@Qalthos Thanks for taking a look at it
